//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISC_Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class bas_Goods
    {
        [Key]
        public string goodsID { get; set; }
        public string extGoodsID { get; set; }
        public string goodsName { get; set; }
        public string tradeName { get; set; }
        public string factory { get; set; }
        public string spec { get; set; }
        public string unit { get; set; }
        public string spellCode { get; set; }
        public string goodsType { get; set; }
        public string extGoodsType { get; set; }
        public string goodsCode { get; set; }
        public string supervisionCode { get; set; }
        public string valid { get; set; }
        public string updateMan { get; set; }
        public System.DateTime updateTime { get; set; }
    }
}
