//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISC_Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class biz_OutStockDt
    {
        [Key]
        [Column(Order = 1)]
        public string terminalID { get; set; }
        [Key]
        [Column(Order = 2)]
        public string orderID { get; set; }
        [Key]
        [Column(Order = 3)]
        public string detailID { get; set; }
        public string goodsID { get; set; }
        public string batchNo { get; set; }
        public Nullable<System.DateTime> expiryDate { get; set; }
        public Nullable<System.DateTime> productDate { get; set; }
        public decimal orderNum { get; set; }
        public decimal actualNum { get; set; }
        public string RFIDCode { get; set; }
        public string barcode { get; set; }
        public string locatorID { get; set; }
        public string status { get; set; }
        public string updateMan { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
    }
}
