//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISC_Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class biz_GoodsLog
    {
        [Key]
        public int logID { get; set; }
        public string terminalID { get; set; }
        public string operationtype { get; set; }
        public string goodsID { get; set; }
        public string batchNo { get; set; }
        public System.DateTime expiryDate { get; set; }
        public System.DateTime productDate { get; set; }
        public string locatorID { get; set; }
        public string RFID { get; set; }
        public string barCode { get; set; }
        public decimal actualNum { get; set; }
        public string operator1 { get; set; }
        public string operator2 { get; set; }
        public string operator3 { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public string orderID { get; set; }
        public string detailID { get; set; }
    }
}
