//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISC_Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class biz_RFIDLog
    {
        [Key]
        public int id { get; set; }
        public string terminalID { get; set; }
        public string orderNo { get; set; }
        public string type { get; set; }
        public string RFID { get; set; }
        public string locatorID { get; set; }
        public string updateMan { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
        public string status { get; set; }
    }
}
