//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISC_Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class biz_OutStockAddtion
    {
        [Key]
        [Column(Order = 1)]
        public string terminalID { get; set; }
        [Key]
        [Column(Order = 2)]
        public string addtionID { get; set; }
        public System.DateTime addtionTime { get; set; }
        public string patientID { get; set; }
        public string patientName { get; set; }
        public string patientSpellCode { get; set; }
        public int patientAge { get; set; }
        public string patientSex { get; set; }
        public string patientDept { get; set; }
        public string bedNo { get; set; }
        public string operateName { get; set; }
        public string execDept { get; set; }
        public string orderID { get; set; }
        public string status { get; set; }
    }
}
