//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISC_Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class interface_InStock_RF
    {
        [Key]
        [Column(Order = 1)]
        public string orderID { get; set; }
        [Key]
        [Column(Order = 2)]
        public string orderdetailID { get; set; }
        public string supplier { get; set; }
        public string deptID { get; set; }
        [Key]
        [Column(Order = 3)]
        public string terminalID { get; set; }
        public string goodsID { get; set; }
        public Nullable<System.DateTime> validityDate { get; set; }
        public Nullable<System.DateTime> produceDate { get; set; }
        public string batchNo { get; set; }
        public Nullable<decimal> num { get; set; }
        public string RFID { get; set; }
        public string creator { get; set; }
        public string extLocatorID { get; set; }
        public Nullable<System.DateTime> orderTime { get; set; }
        public Nullable<System.DateTime> receiveTime { get; set; }
        public string status { get; set; }
    }
}
