//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISC_Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class interface_backSPD_RF
    {
        [Key]
        public int ID { get; set; }
        public string goodsID { get; set; }
        public string RFID { get; set; }
        public string terminalID { get; set; }
        public string orderID { get; set; }
        public string patientID { get; set; }
        public string patientName { get; set; }
        public string patientAge { get; set; }
        public string patientSex { get; set; }
        public string patientDept { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public string status { get; set; }
        public string remark { get; set; }
    }
}
