//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISC_Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sys_Log
    {
        [Key]
        public string logID { get; set; }
        public string terminalID { get; set; }
        public string clientIP { get; set; }
        public string logType { get; set; }
        public string moduleID { get; set; }
        public string @operator { get; set; }
        public System.DateTime operatorTime { get; set; }
        public string remark { get; set; }
    }
}
