//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISC_Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sys_OrderNo
    {
        public string OrderClass { get; set; }
        public Nullable<int> YearNum { get; set; }
        public Nullable<int> MonthNum { get; set; }
        public Nullable<int> DayNum { get; set; }
        public string OrderNo { get; set; }
        [Key]
        public int ID { get; set; }
    }
}
